### PR TITLE
Cause errors to be raise outside the TimingTest loop.

### PR DESCRIPTION
**Pull request by mithro**
This means even if there is an error, the rest of the tests / callbacks are run.

### CODE REVIEW

**Comment by dstoc** [comment]
Why do we want to do this?

**Comment by mithro** [comment]
See the comment. It means that an error doesn't stop the rest of the tests
from executing. Just a try/catch would then how the errors.

**Comment by dstoc** [comment]
> See the comment. It means that an error doesn't stop the rest of the tests
> from executing. Just a try/catch would then how the errors.

I mean, why wouldn't we want to stop the rest of the tests/callbacks from executing?

**Comment by mithro** [comment]
When viewed in the test-runner the whole page displays a timeout rather then providing a useful error message.

**Pull request merged**
