### PR TITLE
Fixes to work with SVG files

### PR DESCRIPTION
**Pull request by birtles**

### CODE REVIEW

**Comment by birtles** [comment]
Apparently the lint tool doesn't like ? and : at the start of the line. Will fix some day.

**Comment by dstoc** [comment]
lgtm

> Apparently the lint tool doesn't like ? and : at the start of the line. Will fix some day.

Yes, need to break after binary operators.

**Comment by birtles** [comment]
Wow, that is amazing, how did it know I wanted to add that commit to this pull request?

**Comment by birtles** [comment]
Ping?

**Pull request merged**
