### PR TITLE
Added slide functionality & user pause

### PR DESCRIPTION
**Pull request by StephMc**

### CODE REVIEW

**Comment by steveblock** [comment]
Nice - just a few small things

**Comment by StephMc** [comment]
I've updated the code with the suggested changes.

**Comment by steveblock** [comment]
Just a couple more things

**Comment by StephMc** [comment]
I've updated the code with the suggested changes.

**Comment by StephMc** [comment]
I've updated the code with the suggested changes.

**Comment by steveblock** [comment]
One minor thing, which you can address later.

**Pull request merged**
