### PR TITLE
Preparatory work for chained timing functions

### PR DESCRIPTION
**Pull request by steveblock**

### CODE REVIEW

**Comment by shans** [comment]
LGTM.

**Comment by dstoc** [comment]
Tests fail in firefox: http://postimg.org/image/u6oybw5iv/

**Comment by steveblock** [comment]
Rebased and added failing expectations for Firefox (it looks like Firefox has fundamental problems with path effects)

**Comment by steveblock** [comment]
I had to drop the commit to update the expected results for auto-test-timing-functions.html because I ran into rounding errors on Firefox and IE.

**Pull request merged**
