### PR TITLE
Use ES5 getters and setters as well as __proto__ where available.

### PR DESCRIPTION
**Pull request by arv**
This fixes pure JS issues with IE9+

This cleans up the code to use ES5 getters and setters in the object literals instead of reflection methods.

This also uses **proto** in the object literals (wrapped in createObject for IE support)

### CODE REVIEW

**Comment by steveblock** [comment]
Thanks Erik. Just a couple of minor things, but it looks like this will need rebasing anyway.

**Comment by arv** [comment]
configureDescriptor is still used.

Where is the indentation wrong? The comment is not attached to the code

**Comment by arv** [comment]
PTAL

**Comment by steveblock** [comment]
LGTM

Will leave it to Dmitry

**Comment by DmitryBaranovskiy** [comment]
LGTM. :)

**Comment by steveblock** [comment]
It looks like this needs rebasing - if you can do so I'll merge it.

**Comment by arv** [comment]
Rebased

**Pull request merged**
