### PR TITLE
Adding a setting framework to the test-harness.

### PR DESCRIPTION
**Pull request by mithro**
settings

### CODE REVIEW

**Comment by mithro** [comment]
JSON.parse("sdfsadf"); doesn't return "sdfsadf" like this function does. I guess I could do a 

``` javascript
var output = null;
try {
  output = JSON.parse(input);
} catch {
  output = input;
}
```

What do you think?

**Comment by shans** [comment]
This change adds significant complexity, but I don't see why we need a settings
framework at the moment.  Something Doug, Steve and I have fallen into the
habit of doing is whiteboarding more complicated changes before starting to
code them. Perhaps we should do that for settings?

**Comment by mithro** [comment]
I didn't really understand this problem until I had a possible solution, it came out of trying to add a GUI to control the various features we want to support. I'm happy to discuss this change further on the whiteboard if you want.

**Comment by mithro** [comment]
RE: Why I ended up creating this;
- We currently have 2 different ways of setting "options", one via the script tag and one via the hash part of the UI. I'd like to make using the query string version to also work.
- How options work is currently inconsistent in how they work, IE some are "noXXX" while others are "XXX=false". 
- Extracting the options from query string is actually harder than it looks, in this process discovered bugs where if the setting was the first option or last option the system wouldn't work properly.
- Manipulating the query string is actually quite hard under Javascript, you need to remove the previous setting and add the new setting. Just appending a new value is fraught with danger and confusing.
- Settings come from multiple places, we have bootstrap.js settings, timing settings, extension settings. This is only going to get worse.
- All the above effect the creation of a GUI elements to control these settings.

While attempting to fix the above problems I ended up repeating very similar code in multiple locations, hence the refactoring towards having a settings framework.

**Comment by mithro** [comment]
BTW Still very happy to discuss this change further on the whiteboard if you want.

**Pull request closed without merging**
